name: Deploy AWS Lambda with CDK

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: "ASIA4IM3HLT6XCJESMBV"
          aws-secret-access-key: "hhsyBhDlYDO9Kc6R7iOtqMuUSL6wtnW3wBO57EwT"
          aws-session-token: "IQoJb3JpZ2luX2VjEOH//////////wEaDGNhLWNlbnRyYWwtMSJHMEUCIQDsX8/zZNpxYumL5YOuE0tdF545bhvH/Zy/YnGggvllpQIgOYd9n+Pn0BV4DrzG2D454SqauGhNG2DJnRA6jowANAAq+wIIexAAGgw4NDI2NzYwMDIwNDUiDMEXzHQ0g8ZFSLGMJCrYAg8IIZ5GDAA14e4jP0p9HUSPL9TQS1AFYPp/c3qPamVl8khEsBLoBMurcR4eOREUmn7M4bSV2/Pep/0vE08RmrSWM/SoQeRSJlC2W1pMch1bI0Vqp/Zz3VJRiqVq2gm57P+ue0nRZAKU41XCw+3AeixMT7rXV96UuAcPuvlQzy3Ky6P/D7M8XMY1Iorp+CULXstRYmLhyCOh5DRKpy7Os3UsYFOIZWz4VLFH1qbZ1bWRmTnhnEfRScui8dbTlyAuTF04UxRcCcxNXqHxIRe2dSefHicf2PK/Q1Uf9gvZRzUWQj3+pTmddOS92XFTyxazBexduEQ9DPU5Fq8RqTSCFvD3HGiomhIIzN5HZhRP5FAegaPSlghgm+nIZA4nPtvHbjomrVhc8bCVdlcZAu843dkAa7/ccK6z8rS//33s2/UZ92HdSGqfpSp5zxGUYuWF+LHzDTIdbZxhMLOW87kGOqcBFOhAMwMlGyXTagyQkKd0Z9Xdt9AN9ZcwAnRsXOjEXtu6cx+mBax676RBl/GbWZsRnRwx4SsquMCjZHzIHw21aOCi6u7hxwcZE7Xxser0TIazvdhGiygXZlFTtBjnK+H3aSMlMJzW9y63AGt4gLu10cW853aUKpC7MauttrGO+8QQLHV6OPoWQEZTJLD+vKfqEwGxOQRufgi6s0FhRvc3qI4Q5XLv1Ss="
          aws-region: "ca-central-1"

      - name: CDK Bootstrap
        working-directory: ./my-cdk-app
        run: npx cdk bootstrap || echo "Bootstrap already done"

      - name: Deploy Stack
        working-directory: ./my-cdk-app
        run: npx cdk deploy --require-approval never