name: Deploy AWS Lambda with CDK

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Clean npm cache and remove node_modules
        working-directory: ./frontend
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --force

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::842676002045:role/permissions_lots
          aws-region: ca-central-1
      
      - name: CDK Bootstrap
        run: npx cdk bootstrap

      - name: Deploy Stack
        run: npx cdk deploy --require-approval never

      - name: Install TypeScript
        run: npm install -g typescript
    
      # Step 8: Build Frontend
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm run build
          if [ ! -d "dist" ]; then
            echo "Build folder not found!"
            exit 1
          fi

      # Step 9: Deploy Frontend to S3 and CloudFront
      # aws s3 sync ./frontend/build s3://YOUR_FRONTEND_BUCKET_NAME --delete
      - name: Deploy Frontend
        run: |
          aws s3 sync ./frontend/dist s3://myfrontendbucket3 --delete
          aws cloudfront create-invalidation --distribution-id E27NHW8AC9BSDB --paths "/*"
          